[package]
name = "spotlight-notes"
version = "0.1.0"
description = "A macOS menu-bar quick-note app with Spotlight-like overlay and scheduled reminders"
authors = ["Isaccseven"]
license = "MIT"
edition = "2021"
repository = "https://github.com/Isaccseven/spotlight-notes"
homepage = "https://github.com/Isaccseven/spotlight-notes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "spotlight_notes_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
tokio = { version = "1", features = ["time", "process", "io-util"] }
tauri-plugin-store = "2"
tauri-plugin-notification = "2"
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
uuid = { version = "1.23.2", features = ["serde", "v4"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"


[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"
