const GLOBAL_SHORTCUTS_KEY = "Command+Shift+W";
const DEBOUNCE_DELAY = 500;

const INSERT_TAG_KEY = "t";
const NEXT_TAG_GROUP_KEY = "g";
const PREV_TAG_GROUP_KEY = "h";
const CYCLE_TAG_KEY = "p";
const REMOVE_TAG_KEY = "x";
const TOGGLE_GROUP_KEY = "b";

export {
  GLOBAL_SHORTCUTS_KEY,
  DEBOUNCE_DELAY,
  INSERT_TAG_KEY,
  NEXT_TAG_GROUP_KEY,
  PREV_TAG_GROUP_KEY,
  CYCLE_TAG_KEY,
  REMOVE_TAG_KEY,
  TOGGLE_GROUP_KEY,
};
